import { Poppins } from "next/font/google";
import "./globals.css";
import Navbar from "@/Shared/Navbar";
import QueryProvider from "@/Provider/QueryProvider/QueryProvider";
import Providers from "@/Provider/providers";
import { Footer } from "@/Shared/Footer";

// Fonts
const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  display: "swap",
});

// Metadata
export const metadata = {
  title: "Next Starter Template",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${poppins.variable} antialiased`}>
        <QueryProvider>
          <Providers>
            <Navbar />
            {children}
            <Footer />
          </Providers>
        </QueryProvider>
      </body>
    </html>
  );
}
